dev_build:
  stage: build
  when: always
  variables:
    # 构建镜像名称
    DOCKER_NAME: $REGISTRY_DOMAIN/$REGISTRY_NAMESPACE/$PROJECT_NAME-test:latest
    APP_MODE: build:dev
  only:
    - dev
  tags:
    - apple
  script:
    # 登录Harbor镜像仓库
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_DOMAIN
    # 构建 Docker 镜像
    - docker build --build-arg BRANCH=$APP_MODE -t $DOCKER_NAME -f .gitlab/Dockerfile .
    # 推送镜像
    - docker image push $DOCKER_NAME
    # 删除 Docker
    - docker image rm -f $DOCKER_NAME
dev_deploy:
  stage: deploy
  image: harbor.ant-lord.com/library/alpine-curl:latest
  variables:
    # 测试环境 https://xac-shop-test.shieye-property.com
    SERVICE_WEBHOOK: https://portainer.ant-lord.com/api/webhooks/442ff342-01ba-4082-9284-a55a9d35d2b4
  only:
    - dev
  tags:
    - apple
  before_script:
    - echo "开始触发 portainer webhook"
  script:
    - curl -X POST --insecure $SERVICE_WEBHOOK